### ISSUE TITLE
这个作者是日本人耶

### ISSUE THREAD

**Issue by dong-lufei** [Ryotaewamoto/math_study#1]
😀

**Comment by Ryotaewamoto** [comment]
@dong-lufei 
Hey! What's happened?

**Comment by dong-lufei** [comment]
@Ryotaewamoto I saw a Japanese developer for the first time and was a little excited

**Comment by Ryotaewamoto** [comment]
> I saw a Japanese developer for the first time and was a little excited

Thanks!! 😄 The communication with a Chinese developer is a first time for me too.

@dong-lufei 
Are you a engineer? or a designer ?

**Comment by dong-lufei** [comment]
@Ryotaewamoto 我用 JavaScript、nodejs、go、java、python

**Comment by Ryotaewamoto** [comment]
我用 Flutter, TypeScript, and a little Python 😆

@dong-lufei 
Great 👍 You work as a software engineer in China? 

And, You are interested in Flutter ? 👇

https://github.com/flutter/flutter/issues/119995

**Comment by dong-lufei** [comment]
嗯，在武汉上班。之前用taro、uni-app，现在用了一点点 flutter。

**Comment by Ryotaewamoto** [comment]
I knew "taro" and "uni-app at the first time!
What are taro and uni-app? It's Flutter mobile application??

**Comment by dong-lufei** [comment]
跨端框架，开发者编写一套代码，可发布到iOS、Android、Web（响应式）、以及各种小程序（微信/支付宝/百度/头条/飞书/QQ/快手/钉钉/淘宝）、快应用等多个平台。

**Comment by Ryotaewamoto** [comment]
Thanks !!
"taro" and "uni-app" are frameworks for creating mobile apps, my understanding is correct ?
Also, these program like codes use React and Vue.js. 
(I read the beginning of [this article](https://juejin.cn/post/6974584590841167879).)

**Comment by dong-lufei** [comment]
好像都是我们中国的产品，可能外国人没听过。
不知道你们能否访问到他们官方网站： https://uniapp.dcloud.net.cn

我们中国有个 app 叫 微信(wechat) 和 支付宝，他们里面又有小程序，微信的叫微信小程序，支付宝的叫支付宝小程序，uni-app 框架是写 小程序 和 app 的

**Comment by Ryotaewamoto** [comment]
Oh~, I didn't open https://uniapp.dcloud.net.cn/.

If we use taro or uni-app, we can make mini-app more faster? I consider that this mini app means a app we can use in a parent app like wechat or 支付宝.

**Comment by dong-lufei** [comment]
嗯 https://github.com/dcloudio/uni-app
https://github.com/NervJS/taro

小程序 在我们中国不只是微信小程序和支付宝小程序，还有别的QQ小程序、百度小程序、抖音小程序、快手小程序等等。
小程序和特点是不需要安装，app 需要安装

taro 主要是写跨端小程序的
uni-app 除了写小程序也可以写 Android 和 IOS 应用
